version: '3.4'

services:
  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8081:80"
    environment:
        - PGADMIN_DEFAULT_EMAIL=admin@cloudcore.cc
        - PGADMIN_DEFAULT_PASSWORD=admin123
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  discountdb:
    container_name: discountdb
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  basketdb:
    container_name: basketdb
    image: redis
    restart: always
    ports:
      - "6379:6379"

  catalogdb:
    container_name: catalogdb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # the line below injects and overrides the environmental variable "ConnectionString" to
      # the docker service name to avoid localhost errors in a container environment
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # this is essentailly the same as above, we are simply adding the redish cache string
      # to override the env settings
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "8001:80"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234"
    ports:
      - "8002:80"

